server:
  port: ${REST_SERVICE_PORT:8087}

spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/postgresdb}
    username: ${POSTGRES_USERNAME:userdb}
    password: ${POSTGRES_PASSWORD:p@ssw0rd}
    driver-class-name: ${POSTGRES_DRIVER_CLASS_NAME:org.postgresql.Driver}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

salt: ${SALT:test}